import type { Metadata } from 'next';
import './globals.css';
import { manrope } from '@/until';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/components/common/ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope.variable}`}>
          {/* grid-col-[300px, minmax(0, 1fr)] , cot trai la 300px , 
        con cot phai la phan con lai va 0, 1fr de khoi tran*/}
          {/* <div className="wrapper grid grid-cols-[300px,minmax(0,1fr)]">
            <aside className="sideba">
              <Sidebar />
            </aside>
            <main>{children}</main>
          </div> */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
